meta:
  url: https://arayaryoma.github.io/onoue-lab-2020/
  title: 知らないと卒業できない HTTP の話
  thumbnail:
  description:
  sns:
    - twitter
slide:
  loop: false
  sidebar: true
  targetBlank: true
  showIndex: true
  isVertical: false
  code:
    languages:
      - javascript
    plugins: []
    theme: default
  chart: false
  math: false
extends:
  js:
  css: ./style.css
build:
  ssr: true
  useCache: true
  publicPath: /
